### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by srpatel19590** [base-org/node#244]
Steps to reproduce:

- download latest mainnet snapshot - `wget https://mainnet-full-snapshots.base.org/$(curl https://mainnet-full-snapshots.base.org/latest)` 
- extract gzip
- Followed the steps written [here](wget https://mainnet-full-snapshots.base.org/$(curl https://mainnet-full-snapshots.base.org/latest)) 
- mv `geth` dir from snapshot into the data-dir `geth-data/`
- docker compose up

Crash Log:

```
geth-1  | panic: runtime error: makeslice: len out of range
geth-1  | 
geth-1  | goroutine 1 [running]:
geth-1  | github.com/syndtr/goleveldb/leveldb.(*sessionRecord).readBytes(0xc000749af8, {0x19f37fb, 0x8}, {0x7fa451462468?, 0xc00015e040})
geth-1  | 	github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_record.go:236 +0xa9
geth-1  | github.com/syndtr/goleveldb/leveldb.(*sessionRecord).decode(0xc000749af8, {0x268c8c0?, 0xc00015e040})
geth-1  | 	github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_record.go:274 +0x2b9
geth-1  | github.com/syndtr/goleveldb/leveldb.(*session).recover(0xc00071c000)
geth-1  | 	github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:170 +0x4a7
geth-1  | github.com/syndtr/goleveldb/leveldb.Open({0x269f278?, 0xc00027efc0?}, 0x0?)
geth-1  | 	github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:189 +0x95
geth-1  | github.com/syndtr/goleveldb/leveldb.OpenFile({0xc00061b680?, 0x1a1eb7c?}, 0xc0003fe000)
geth-1  | 	github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:225 +0x5d
geth-1  | github.com/ethereum/go-ethereum/ethdb/leveldb.NewCustom({0xc00061b680, 0x14}, {0x19fef62, 0x11}, 0x0?)
geth-1  | 	github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:122 +0x305
geth-1  | github.com/ethereum/go-ethereum/ethdb/leveldb.New({0xc00061b680?, 0x25?}, 0x800, 0x80000, {0x19fef62?, 0xc00007bdf0?}, 0x0?)
geth-1  | 	github.com/ethereum/go-ethereum/ethdb/leveldb/leveldb.go:90 +0x6b
geth-1  | github.com/ethereum/go-ethereum/core/rawdb.NewLevelDBDatabase({0xc00061b680?, 0x25?}, 0x0?, 0x0?, {0x19fef62?, 0x0?}, 0x1?)
geth-1  | 	github.com/ethereum/go-ethereum/core/rawdb/database.go:317 +0x25
geth-1  | github.com/ethereum/go-ethereum/core/rawdb.openKeyValueDatabase({{0x0, 0x0}, {0xc00061b680, 0x14}, {0xc00010e3c0, 0x1c}, {0x19fef62, 0x11}, 0x800, 0x80000, ...})
geth-1  | 	github.com/ethereum/go-ethereum/core/rawdb/database.go:394 +0x266
geth-1  | github.com/ethereum/go-ethereum/core/rawdb.Open({{0x0, 0x0}, {0xc00061b680, 0x14}, {0xc00010e3c0, 0x1c}, {0x19fef62, 0x11}, 0x800, 0x80000, ...})
geth-1  | 	github.com/ethereum/go-ethereum/core/rawdb/database.go:407 +0x45
geth-1  | github.com/ethereum/go-ethereum/node.(*Node).OpenDatabaseWithFreezer(0xc0001b95e0, {0x19f42e6, 0x9}, 0x800, 0x80000, {0x0, 0x0}, {0x19fef62, 0x11}, 0x0)
geth-1  | 	github.com/ethereum/go-ethereum/node/node.go:758 +0x338
geth-1  | github.com/ethereum/go-ethereum/eth.New(0xc0001b95e0, 0xc00025e300)
geth-1  | 	github.com/ethereum/go-ethereum/eth/backend.go:139 +0x513
geth-1  | github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc0004460d0?, 0x19fb9f8?)
geth-1  | 	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1995 +0x25
geth-1  | main.makeFullNode(0xc0004b1bc8?)
geth-1  | 	github.com/ethereum/go-ethereum/cmd/geth/config.go:197 +0x3f2
geth-1  | main.geth(0xc0002168c0)
geth-1  | 	github.com/ethereum/go-ethereum/cmd/geth/main.go:361 +0xe5
geth-1  | github.com/urfave/cli/v2.(*Command).Run(0xc0001ac000, 0xc0002168c0, {0xc0000401e0, 0x1e, 0x1e})
geth-1  | 	github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x998
geth-1  | github.com/urfave/cli/v2.(*App).RunContext(0xc000040960, {0x26955e8?, 0x3412b20}, {0xc0000401e0, 0x1e, 0x1e})
geth-1  | 	github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x5b7
geth-1  | github.com/urfave/cli/v2.(*App).Run(...)
geth-1  | 	github.com/urfave/cli/v2@v2.25.7/app.go:309
geth-1  | main.main()
geth-1  | 	github.com/ethereum/go-ethereum/cmd/geth/main.go:281 +0x45
```

It is working fine without snapshot data.

**Comment by wbnns** [comment]
@srpatel19590

Hello, thanks for reporting this issue! Please join the [Base Discord](https://base.org/discord) and open a ticket in the `#developer-support` channel.

On Discord we can take a closer look at your specific configuration to see what the issue might be.
