### ISSUE TITLE
Failing to build image

### ISSUE THREAD

**Issue by crisog** [base-org/node#71]
OS: Debian GNU/Linux 11 (bullseye)
Docker Engine Version: 20.10.6
Docker Compose Version: v2.3.3

Reproduce:
1. Updated the config as required for mainnet.
2. Run `docker compose up --build`, but it didn't work.
```bash
2 errors occurred:
	* Error response from daemon: dockerfile parse error line 9: Unknown flag: checksum
```
Got it working by adding this variable
```bash
DOCKER_BUILDKIT=1 docker compose up --build
```

It got to the build stage, but it also failed there with the following error:
<details>
  <summary>Expand to see error details</summary>
  
  ```bash
  [+] Building 2.6s (22/33)                                                                                                                               
 => [node_node internal] load build definition from Dockerfile                                                                                     0.0s
 => => transferring dockerfile: 32B                                                                                                                0.0s
 => [node_geth internal] load build definition from Dockerfile                                                                                     0.0s
 => => transferring dockerfile: 32B                                                                                                                0.0s
 => [node_node internal] load .dockerignore                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [node_geth internal] load .dockerignore                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [node_geth] resolve image config for docker.io/docker/dockerfile:1-labs                                                                        0.3s
 => CACHED [node_geth] docker-image://docker.io/docker/dockerfile:1-labs@sha256:f2e91734a84c0922ff47aa4098ab775f1dfa932430d2888dd5cad5251fafdac4   0.0s
 => [node_node internal] load .dockerignore                                                                                                        0.0s
 => [node_node internal] load build definition from Dockerfile                                                                                     0.0s
 => [node_node internal] load metadata for docker.io/library/golang:1.19                                                                           0.3s
 => [node_geth internal] load .dockerignore                                                                                                        0.0s
 => [node_geth internal] load build definition from Dockerfile                                                                                     0.0s
 => [node_node internal] load build context                                                                                                        0.0s
 => => transferring context: 294B                                                                                                                  0.0s
 => [node_geth] https://github.com/ethereum-optimism/optimism/archive/op-node/v1.1.1.tar.gz                                                        0.0s
 => [node_geth] https://github.com/ethereum-optimism/op-geth/archive/v1.101106.0.tar.gz                                                            0.0s
 => CACHED [node_node geth 1/4] FROM docker.io/library/golang:1.19@sha256:2c99dd5bc507faba422eb0a2661b675250001815a08335a8cc98af196d0291db         0.0s
 => CACHED [node_geth geth 2/4] WORKDIR /app                                                                                                       0.0s
 => CACHED [node_node op 3/4] ADD --checksum=sha256:c0f3dbce8729016103b8390f9ee81089cd858242df6a45a42c59555f1c9e9106 https://github.com/ethereum-  0.0s
 => CACHED [node_geth geth 3/4] ADD --checksum=sha256:0273ea3226147ba5b04c1a6eff2d9da48e6bbff3a348b33fe13e7e34d88ba411 https://github.com/ethereu  0.0s
 => [node_geth internal] load build context                                                                                                        0.0s
 => => transferring context: 294B                                                                                                                  0.0s
 => ERROR [node_geth op 4/4] RUN tar -xvf ./v1.1.1.tar.gz --strip-components=1 &&     cd op-node &&     make op-node                               1.6s
 => ERROR [node_node geth 4/4] RUN tar -xvf ./v1.101106.0.tar.gz --strip-components=1 &&     go run build/ci.go install -static ./cmd/geth         1.6s
 => CANCELED [node_node stage-2 2/9] RUN apt-get update &&     apt-get install -y jq curl &&     rm -rf /var/lib/apt/lists                         1.7s
------                                                                                                                                                  
 > [node_geth op 4/4] RUN tar -xvf ./v1.1.1.tar.gz --strip-components=1 &&     cd op-node &&     make op-node:  
 #18 0.523 optimism-op-node-v1.1.1/.changeset/       
 [OMITTED]
 #18 1.432 make: git: Operation not permitted
#18 1.432 make: git: Operation not permitted
#18 1.454 make: git: Operation not permitted
#18 1.454 make: git: Operation not permitted
#18 1.433 env GO111MODULE=on GOOS= GOARCH= go build -v -ldflags "-X main.GitCommit= -X main.GitDate= -X github.com/ethereum-optimism/optimism/op-node/version.Version=v0.0.0 -X github.com/ethereum-optimism/optimism/op-node/version.Meta=" -o ./bin/op-node ./cmd/main.go
#18 1.455 env GO111MODULE=on GOOS= GOARCH= go build -v -ldflags "-X main.GitCommit= -X main.GitDate= -X github.com/ethereum-optimism/optimism/op-node/version.Version=v0.0.0 -X github.com/ethereum-optimism/optimism/op-node/version.Meta=" -o ./bin/op-node ./cmd/main.go
#18 1.455 make: /bin/sh: Operation not permitted
#18 1.455 make: *** [Makefile:12: op-node] Error 127
#18 1.433 make: /bin/sh: Operation not permitted
#18 1.433 make: *** [Makefile:12: op-node] Error 127
------
------
 > [node_node geth 4/4] RUN tar -xvf ./v1.101106.0.tar.gz --strip-components=1 &&     go run build/ci.go install -static ./cmd/geth:
#22 0.762 op-geth-1.101106.0/.circleci/
[OMITTED]
#22 1.546 runtime/cgo: pthread_create failed: Operation not permitted
#22 1.567 runtime/cgo: pthread_create failed: Operation not permitted
#22 1.570 SIGABRT: abort
#22 1.570 PC=0x7f9dc8d00ccc m=0 sigcode=18446744073709551610
#22 1.570 
#22 1.570 goroutine 0 [idle]:
#22 1.570 runtime: g 0: unknown pc 0x7f9dc8d00ccc
#22 1.570 stack: frame={sp:0x7ffe1208c800, fp:0x0} stack=[0x7ffe1188dc80,0x7ffe1208cc90)
#22 1.570 0x00007ffe1208c700:  0x00007ffe1208c950  0x0000000000000000 
#22 1.570 0x00007ffe1208c710:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c720:  0x0000000000000000  0x0000000000429865 <runtime.(*mheap).alloc+0x0000000000000065> 
#22 1.570 0x00007ffe1208c730:  0x0000000000203000  0x0000000000000400 
#22 1.570 0x00007ffe1208c740:  0x0000000000000002  0x800000000000000e 
#22 1.570 0x00007ffe1208c750:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c760:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c770:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c780:  0x0000000000a290c9  0x0000000000000006 
#22 1.570 0x00007ffe1208c790:  0x0000000000e6e26a  0x0000000000000000 
#22 1.570 0x00007ffe1208c7a0:  0x0000000000a281ea  0x0000000000000004 
#22 1.570 0x00007ffe1208c7b0:  0x0000000000e6e26c  0x0000000000000000 
#22 1.570 0x00007ffe1208c7c0:  0x0000000000a28854  0x0000000000000005 
#22 1.570 0x00007ffe1208c7d0:  0x0000000000000000  0x00007f9dc8d6e134 
#22 1.570 0x00007ffe1208c7e0:  0x0000000000000000  0x000000000000000d 
#22 1.570 0x00007ffe1208c7f0:  0x0000000000b2c5e6  0x00007f9dc8d00cbe 
#22 1.570 0x00007ffe1208c800: <0x0000000000000000  0x5043571b43089100 
#22 1.570 0x00007ffe1208c810:  0x0000000000000006  0x00007f9dc8c73740 
#22 1.570 0x00007ffe1208c820:  0x00000000015282e0  0x0000000000000178 
#22 1.570 0x00007ffe1208c830:  0x0000000000e3cda0  0x00007f9dc8cb1ef2 
#22 1.570 0x00007ffe1208c840:  0x00007f9dc8e49e70  0x00007f9dc8c9c472 
#22 1.570 0x00007ffe1208c850:  0x0000000000000020  0x00007f9dc8e49703 
#22 1.570 0x00007ffe1208c860:  0x0000000000000d68  0x00007f9dc8cf6220 
#22 1.570 0x00007ffe1208c870:  0x00007f9dc8e455e0  0x0000000000000001 
#22 1.570 0x00007ffe1208c880:  0x000000000000000a  0x00007f9dc8c73740 
#22 1.570 0x00007ffe1208c890:  0x0000000000000178  0x0000000000e3cda0 
#22 1.570 0x00007ffe1208c8a0:  0x00007f9da190235b  0x00007f9dc8cf7e79 
#22 1.570 0x00007ffe1208c8b0:  0x00007f9dc8e49680  0x00007f9dc8cf8283 
#22 1.570 0x00007ffe1208c8c0:  0x00007f9dc8e49680  0x000000000000000a 
#22 1.570 0x00007ffe1208c8d0:  0x00007f9dc8c73740  0x00007f9dc8cf380a 
#22 1.570 0x00007ffe1208c8e0:  0x00007f9dc8e49840  0x5043571b43089100 
#22 1.570 0x00007ffe1208c8f0:  0x00007f9dc8e49840  0x00007f9dc8e49840 
#22 1.570 runtime: g 0: unknown pc 0x7f9dc8d00ccc
#22 1.570 stack: frame={sp:0x7ffe1208c800, fp:0x0} stack=[0x7ffe1188dc80,0x7ffe1208cc90)
#22 1.570 0x00007ffe1208c700:  0x00007ffe1208c950  0x0000000000000000 
#22 1.570 0x00007ffe1208c710:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c720:  0x0000000000000000  0x0000000000429865 <runtime.(*mheap).alloc+0x0000000000000065> 
#22 1.570 0x00007ffe1208c730:  0x0000000000203000  0x0000000000000400 
#22 1.570 0x00007ffe1208c740:  0x0000000000000002  0x800000000000000e 
#22 1.570 0x00007ffe1208c750:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c760:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c770:  0x0000000000000000  0x0000000000000000 
#22 1.570 0x00007ffe1208c780:  0x0000000000a290c9  0x0000000000000006 
#22 1.570 0x00007ffe1208c790:  0x0000000000e6e26a  0x0000000000000000 
#22 1.570 0x00007ffe1208c7a0:  0x0000000000a281ea  0x0000000000000004 
#22 1.570 0x00007ffe1208c7b0:  0x0000000000e6e26c  0x0000000000000000 
#22 1.570 0x00007ffe1208c7c0:  0x0000000000a28854  0x0000000000000005 
#22 1.570 0x00007ffe1208c7d0:  0x0000000000000000  0x00007f9dc8d6e134 
#22 1.570 0x00007ffe1208c7e0:  0x0000000000000000  0x000000000000000d 
#22 1.570 0x00007ffe1208c7f0:  0x0000000000b2c5e6  0x00007f9dc8d00cbe 
#22 1.570 0x00007ffe1208c800: <0x0000000000000000  0x5043571b43089100 
#22 1.570 0x00007ffe1208c810:  0x0000000000000006  0x00007f9dc8c73740 
#22 1.570 0x00007ffe1208c820:  0x00000000015282e0  0x0000000000000178 
#22 1.570 0x00007ffe1208c830:  0x0000000000e3cda0  0x00007f9dc8cb1ef2 
#22 1.570 0x00007ffe1208c840:  0x00007f9dc8e49e70  0x00007f9dc8c9c472 
#22 1.570 0x00007ffe1208c850:  0x0000000000000020  0x00007f9dc8e49703 
#22 1.570 0x00007ffe1208c860:  0x0000000000000d68  0x00007f9dc8cf6220 
#22 1.570 0x00007ffe1208c870:  0x00007f9dc8e455e0  0x0000000000000001 
#22 1.570 0x00007ffe1208c880:  0x000000000000000a  0x00007f9dc8c73740 
#22 1.570 0x00007ffe1208c890:  0x0000000000000178  0x0000000000e3cda0 
#22 1.570 0x00007ffe1208c8a0:  0x00007f9da190235b  0x00007f9dc8cf7e79 
#22 1.570 0x00007ffe1208c8b0:  0x00007f9dc8e49680  0x00007f9dc8cf8283 
#22 1.570 0x00007ffe1208c8c0:  0x00007f9dc8e49680  0x000000000000000a 
#22 1.570 0x00007ffe1208c8d0:  0x00007f9dc8c73740  0x00007f9dc8cf380a 
#22 1.570 0x00007ffe1208c8e0:  0x00007f9dc8e49840  0x5043571b43089100 
#22 1.570 0x00007ffe1208c8f0:  0x00007f9dc8e49840  0x00007f9dc8e49840 
#22 1.570 
#22 1.570 goroutine 1 [running]:
#22 1.570 runtime.systemstack_switch()
#22 1.570 	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc000052780 sp=0xc000052778 pc=0x4662e0
#22 1.570 runtime.main()
#22 1.570 	/usr/local/go/src/runtime/proc.go:170 +0x6d fp=0xc0000527e0 sp=0xc000052780 pc=0x439ded
#22 1.570 runtime.goexit()
#22 1.570 	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x468501
#22 1.570 
#22 1.570 rax    0x0
#22 1.570 rbx    0x9
#22 1.570 rcx    0x7f9dc8d00ccc
#22 1.570 rdx    0x6
#22 1.570 rdi    0x9
#22 1.570 rsi    0x9
#22 1.570 rbp    0x7f9dc8c73740
#22 1.570 rsp    0x7ffe1208c800
#22 1.570 r8     0x0
#22 1.570 r9     0x73
#22 1.570 r10    0x8
#22 1.570 r11    0x246
#22 1.570 r12    0x6
#22 1.570 r13    0x178
#22 1.570 r14    0xe3cda0
#22 1.570 r15    0x7f9da190235b
#22 1.570 rip    0x7f9dc8d00ccc
#22 1.570 rflags 0x246
#22 1.570 cs     0x33
#22 1.570 fs     0x0
#22 1.570 gs     0x0
#22 1.549 SIGABRT: abort
#22 1.549 PC=0x7f9dc8d00ccc m=0 sigcode=18446744073709551610
#22 1.549 
#22 1.549 goroutine 0 [idle]:
#22 1.549 runtime: g 0: unknown pc 0x7f9dc8d00ccc
#22 1.549 stack: frame={sp:0x7ffe1208c800, fp:0x0} stack=[0x7ffe1188dc80,0x7ffe1208cc90)
#22 1.549 0x00007ffe1208c700:  0x00007ffe1208c950  0x0000000000000000 
#22 1.549 0x00007ffe1208c710:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c720:  0x0000000000000000  0x0000000000429865 <runtime.(*mheap).alloc+0x0000000000000065> 
#22 1.549 0x00007ffe1208c730:  0x0000000000203000  0x0000000000000400 
#22 1.549 0x00007ffe1208c740:  0x0000000000000002  0x800000000000000e 
#22 1.549 0x00007ffe1208c750:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c760:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c770:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c780:  0x0000000000a290c9  0x0000000000000006 
#22 1.549 0x00007ffe1208c790:  0x0000000000e6e26a  0x0000000000000000 
#22 1.549 0x00007ffe1208c7a0:  0x0000000000a281ea  0x0000000000000004 
#22 1.549 0x00007ffe1208c7b0:  0x0000000000e6e26c  0x0000000000000000 
#22 1.549 0x00007ffe1208c7c0:  0x0000000000a28854  0x0000000000000005 
#22 1.549 0x00007ffe1208c7d0:  0x0000000000000000  0x00007f9dc8d6e134 
#22 1.549 0x00007ffe1208c7e0:  0x0000000000000000  0x000000000000000d 
#22 1.549 0x00007ffe1208c7f0:  0x0000000000b2c5e6  0x00007f9dc8d00cbe 
#22 1.549 0x00007ffe1208c800: <0x0000000000000000  0x5043571b43089100 
#22 1.549 0x00007ffe1208c810:  0x0000000000000006  0x00007f9dc8c73740 
#22 1.549 0x00007ffe1208c820:  0x00000000015282e0  0x0000000000000178 
#22 1.549 0x00007ffe1208c830:  0x0000000000e3cda0  0x00007f9dc8cb1ef2 
#22 1.549 0x00007ffe1208c840:  0x00007f9dc8e49e70  0x00007f9dc8c9c472 
#22 1.549 0x00007ffe1208c850:  0x0000000000000020  0x00007f9dc8e49703 
#22 1.549 0x00007ffe1208c860:  0x0000000000000d68  0x00007f9dc8cf6220 
#22 1.549 0x00007ffe1208c870:  0x00007f9dc8e455e0  0x0000000000000001 
#22 1.549 0x00007ffe1208c880:  0x000000000000000a  0x00007f9dc8c73740 
#22 1.549 0x00007ffe1208c890:  0x0000000000000178  0x0000000000e3cda0 
#22 1.549 0x00007ffe1208c8a0:  0x00007f9da190235b  0x00007f9dc8cf7e79 
#22 1.549 0x00007ffe1208c8b0:  0x00007f9dc8e49680  0x00007f9dc8cf8283 
#22 1.549 0x00007ffe1208c8c0:  0x00007f9dc8e49680  0x000000000000000a 
#22 1.549 0x00007ffe1208c8d0:  0x00007f9dc8c73740  0x00007f9dc8cf380a 
#22 1.549 0x00007ffe1208c8e0:  0x00007f9dc8e49840  0x5043571b43089100 
#22 1.549 0x00007ffe1208c8f0:  0x00007f9dc8e49840  0x00007f9dc8e49840 
#22 1.549 runtime: g 0: unknown pc 0x7f9dc8d00ccc
#22 1.549 stack: frame={sp:0x7ffe1208c800, fp:0x0} stack=[0x7ffe1188dc80,0x7ffe1208cc90)
#22 1.549 0x00007ffe1208c700:  0x00007ffe1208c950  0x0000000000000000 
#22 1.549 0x00007ffe1208c710:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c720:  0x0000000000000000  0x0000000000429865 <runtime.(*mheap).alloc+0x0000000000000065> 
#22 1.549 0x00007ffe1208c730:  0x0000000000203000  0x0000000000000400 
#22 1.549 0x00007ffe1208c740:  0x0000000000000002  0x800000000000000e 
#22 1.549 0x00007ffe1208c750:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c760:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c770:  0x0000000000000000  0x0000000000000000 
#22 1.549 0x00007ffe1208c780:  0x0000000000a290c9  0x0000000000000006 
#22 1.549 0x00007ffe1208c790:  0x0000000000e6e26a  0x0000000000000000 
#22 1.549 0x00007ffe1208c7a0:  0x0000000000a281ea  0x0000000000000004 
#22 1.549 0x00007ffe1208c7b0:  0x0000000000e6e26c  0x0000000000000000 
#22 1.549 0x00007ffe1208c7c0:  0x0000000000a28854  0x0000000000000005 
#22 1.549 0x00007ffe1208c7d0:  0x0000000000000000  0x00007f9dc8d6e134 
#22 1.549 0x00007ffe1208c7e0:  0x0000000000000000  0x000000000000000d 
#22 1.549 0x00007ffe1208c7f0:  0x0000000000b2c5e6  0x00007f9dc8d00cbe 
#22 1.549 0x00007ffe1208c800: <0x0000000000000000  0x5043571b43089100 
#22 1.549 0x00007ffe1208c810:  0x0000000000000006  0x00007f9dc8c73740 
#22 1.549 0x00007ffe1208c820:  0x00000000015282e0  0x0000000000000178 
#22 1.549 0x00007ffe1208c830:  0x0000000000e3cda0  0x00007f9dc8cb1ef2 
#22 1.549 0x00007ffe1208c840:  0x00007f9dc8e49e70  0x00007f9dc8c9c472 
#22 1.549 0x00007ffe1208c850:  0x0000000000000020  0x00007f9dc8e49703 
#22 1.549 0x00007ffe1208c860:  0x0000000000000d68  0x00007f9dc8cf6220 
#22 1.549 0x00007ffe1208c870:  0x00007f9dc8e455e0  0x0000000000000001 
#22 1.549 0x00007ffe1208c880:  0x000000000000000a  0x00007f9dc8c73740 
#22 1.549 0x00007ffe1208c890:  0x0000000000000178  0x0000000000e3cda0 
#22 1.549 0x00007ffe1208c8a0:  0x00007f9da190235b  0x00007f9dc8cf7e79 
#22 1.549 0x00007ffe1208c8b0:  0x00007f9dc8e49680  0x00007f9dc8cf8283 
#22 1.549 0x00007ffe1208c8c0:  0x00007f9dc8e49680  0x000000000000000a 
#22 1.549 0x00007ffe1208c8d0:  0x00007f9dc8c73740  0x00007f9dc8cf380a 
#22 1.549 0x00007ffe1208c8e0:  0x00007f9dc8e49840  0x5043571b43089100 
#22 1.549 0x00007ffe1208c8f0:  0x00007f9dc8e49840  0x00007f9dc8e49840 
#22 1.549 
#22 1.549 goroutine 1 [running]:
#22 1.549 runtime.systemstack_switch()
#22 1.549 	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc000052780 sp=0xc000052778 pc=0x4662e0
#22 1.549 runtime.main()
#22 1.549 	/usr/local/go/src/runtime/proc.go:170 +0x6d fp=0xc0000527e0 sp=0xc000052780 pc=0x439ded
#22 1.549 runtime.goexit()
#22 1.549 	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x468501
#22 1.549 
#22 1.549 rax    0x0
#22 1.549 rbx    0x9
#22 1.549 rcx    0x7f9dc8d00ccc
#22 1.549 rdx    0x6
#22 1.549 rdi    0x9
#22 1.549 rsi    0x9
#22 1.549 rbp    0x7f9dc8c73740
#22 1.549 rsp    0x7ffe1208c800
#22 1.549 r8     0x0
#22 1.549 r9     0x73
#22 1.549 r10    0x8
#22 1.549 r11    0x246
#22 1.549 r12    0x6
#22 1.549 r13    0x178
#22 1.549 r14    0xe3cda0
#22 1.549 r15    0x7f9da190235b
#22 1.549 rip    0x7f9dc8d00ccc
#22 1.549 rflags 0x246
#22 1.549 cs     0x33
#22 1.549 fs     0x0
#22 1.549 gs     0x0
------
failed to solve: executor failed running [/bin/sh -c tar -xvf ./$VERSION.tar.gz --strip-components=1 &&     go run build/ci.go install -static ./cmd/geth]: exit code: 2
  ```
</details>

**Comment by crisog** [comment]
Updated Docker Engine to `24.0.4` and it worked. It would be nice to find out at which version exactly it breaks and put is as a requirement in the README.
